execution:
  - concurrency: 100
    hold-for: 5m
    ramp-up: 2m
    scenario: sample

scenarios:
  sample:
    headers:
      Connection: close
    requests:
      - http://akvelon-app-lb-743841457.eu-west-1.elb.amazonaws.com:8080
